spring.application.name=staffmanagementsystem

spring.datasource.url=jdbc:sqlserver://LAPTOP-SMG5GGE9\\SQLEXPRESS:1433;databaseName=QLLTBV;encrypt=false;trustServerCertificate=true;
spring.datasource.username=Emris
spring.datasource.password=Emris0410

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app.jwt.secret=MY_SUPER_STRONG_SECRET_KEY_2025_ABCXYZ123456!!
app.jwt.expiration-ms=86400000